### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by kassane** [cv8minix3/Traducao_Guia_Beejs_Sockets_em_C_PTBR#1]
Primeiramente, parabéns pelo trabalho e iniciativa a tradução ficou excelente. Pois este tipo de material é escasso em nosso idioma. Aliás até tentei algo parecido mas de outro projeto voltado para C++ Asio: https://github.com/kassane/ebook-net-prog

Pretende atualiza-lo para v3.1.2 (November 13, 2019)?

**Comment by cv8minix3** [comment]
> Primeiramente, parabéns pelo trabalho e iniciativa a tradução ficou excelente. Pois este tipo de material é escasso em nosso idioma. Aliás até tentei algo parecido mas de outro projeto voltado para C++ Asio: https://github.com/kassane/ebook-net-prog
> 
> Pretende atualiza-lo para v3.1.2 (November 13, 2019)?

Olá, obrigado!
Pretendo sim, acabei de organizar tudo e subi as novas versões do livro para tradução, qualquer dia começo.
